---
title: "Final Project Brainstorming"
author: "Natalie Pottschmidt"
date: "2/16/2020"
output: md_document
---

The purpose of this document is to begin coming up with possible ideas for my final project in PSY 525. My project will be about the [Center for Collegiate Mental Health](ccmh.psu.edu) (*p* < .001), but this could take a variety of forms...

# Shiny App
Following in the footsteps of such CCMH Shiny Apps like the [Clinical Load Index](https://ccmh.shinyapps.io/CLI-app/)

## Regional Visualization
There is a lot that could be done with this app idea - the bullet points below could be trimmed to be more feasible for this project

- Break up schools contributing data into different branches
    - State
    - U.S. Region (e.g., Midwest, Northeast, etc.)
- Visualize features of university counseling center (UCC) clients
    - [Standardized Data Set](https://ccmh.psu.edu/standardized-data-set/) -- mouse over on a map
        - Gender identity
        - Sexual orientation
        - Race/ethnicity (% of each)
        - Religion
    - Clinician Identified Client Concerns (CLICC) -- mouse over on a map
        - 5 most common top concerns by geographic break
    - College Counseling Assessment of Psychological Symptoms (CCAPS) -- heatmaps of:
        - CCAPS-34 baseline subscale averages
        - Expressing suicidal ideation, past two weeks (%)
        - Change in subscale scores over treatment course
- Option to further break down by...
    - Type of service schedule offered by center [default: all]
    - University type (public/private) [default: all]
    - Year [default: most recent]
- Where possible (i.e., in a subset of 80-100 schools contributing data every year), look at change over   time of:
    - CCAPS subscale scores at baseline
    - % of clients endorsing SDS
        - prior mental health services
        - prior hospitalizations
        - psychiatric medication use
        - prior non-suicidal self-injury (NSSI)
        - prior suicidal ideation (SI)
        - prior suicide attempt
    - UCC sessions offered
    - UCC utilization
    
## Trajectories of Client Outcomes by Client Characteristics

- Dividing characteristics
    - SDS
        - prior mental health services
        - prior hospitalizations
        - psychiatric medication use
        - prior non-suicidal self-injury (NSSI)
        - prior suicidal ideation (SI)
        - prior suicide attempt
    - CLICC
        - top concern
        - number of presenting concerns checked
    - CCAPS
        - CCAPS-34 subscales by level of clinical severity (i.e., Low, Moderate, or High -- see the               [CCAPS Screen page](https://ccmh.psu.edu/ccaps-screen/))
        - Ordinal responses on items of clinical significance
            - I have thoughts of ending my life
            - I have thoughts of hurting others
            - I have sleep difficulties
- Client Outcomes
    - Post-treatment CCAPS-34 subscale scores
    - Change over the treatment course on CCAPS-34 subscales
    - Number of sessions used
    - Percentage of sessions attended
    - Drop-out

# GitHub webpage
Most likely a page like this would be used by the CCMH Business Team at PSU

- How-To's 
- Resources
- Profile pages

# Mini Research Reports/Visualizations

## Binge drinking

- Number/percentage of binge drinkers over time
- Trends in the number of drinks per binge for those endorsing them

## Data Mining

- Mentions of CCMH in papers found on PubMed or Google Scholar
- Trends along with CCMH membership
        




